### ISSUE TITLE
adding arguments dynamically

### ISSUE THREAD

**Issue by joachim-n** [consolidation/annotated-command#115]
I see in the docs I can dynamically add an option in the option hook with:

```
$command->addOption()
```

Is there a way to add an argument? Symfony command has an addArgument() method, but I don't see how to get hold of that from somewhere like an interact hook, which is where I'd want to add it based on input.

**Comment by greg-1-anderson** [comment]
How would adding an argument dynamically work? Your hook function is:
```
function myCommand($arg1, $arg2, $options = [...])
{
}
```
If you add an argument dynamically, you would change the function prototype.

You can do this:
```
function myCommand(array $args, $options = [...])
{
}
```
Then the command already takes a variable number of arguments, and there is no need to add any dynamically.

**Comment by joachim-n** [comment]
I was thinking there'd be some way in the interact hook to get hold of the symfony command object and call addArgument() on it...

I'll try the variable args instead.

**Comment by joachim-n** [comment]
BTW the reason I was wanting dynamic arguments, is that the first two arguments for my command are fixed. Therefore, having them set in the annotation as @params and declared on the method meant they were documented.

**Comment by joachim-n** [comment]
> function myCommand(array $args, $options = [...])

That's not working unfortunately:

```
// No arguments:
$ drush9 cbb


  [Symfony\Component\Console\Exception\RuntimeException]
  Not enough arguments (missing: "args").

// Two arguments:
$ drush9 cbb foo bar

  [Symfony\Component\Console\Exception\RuntimeException]
  Too many arguments, expected arguments "command" "args".

```

**Comment by greg-1-anderson** [comment]
Sorry, `array $args` needs at least one arg. `array $args = []` should behave as you want it to.

**Comment by joachim-n** [comment]
That's not working either, sorry:

```
  /**
   * Test variable args.
   *
   * @command cb-foo
   * @param string $args Variable args.
   */
  public function commandFoo(array $args = []) {
    dump('hello!');
  }
```

```
~/Sites/8-drupal joachim$ drush9 cb-foo


  [Symfony\Component\Console\Exception\RuntimeException]
  Not enough arguments (missing: "args").


cb-foo [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-r|--root ROOT] [-l|--uri URI] [-d|--debug] [-y|--yes] [--no] [-p|--pipe] [--php PHP] [-ia|--interactive] [--tty] [-i|--include INCLUDE] [--exclude EXCLUDE] [-c|--config CONFIG] [-b|--backend] [--choice CHOICE] [--search-depth SEARCH-DEPTH] [--ignored-modules IGNORED-MODULES] [--no-label] [--label-separator LABEL-SEPARATOR] [--nocolor] [--show-invoke] [--cache-default-class CACHE-DEFAULT-CLASS] [--cache-class-<bin> CACHE-CLASS-<BIN>] [--early] [--alias-path ALIAS-PATH] [--confirm-rollback] [--php-options PHP-OPTIONS] [--halt-on-error] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [--remote-os REMOTE-OS] [--site-list SITE-LIST] [--reserve-margin RESERVE-MARGIN] [--strict] [--command-specific] [--site-aliases] [--shell-aliases] [--path-aliases] [--ssh-options SSH-OPTIONS] [--drush-coverage] [--local] [--druplicon [DRUPLICON]] [--notify [NOTIFY]] [--notify-audio [NOTIFY-AUDIO]] [--notify-cmd [NOTIFY-CMD]] [--notify-cmd-audio [NOTIFY-CMD-AUDIO]] [--xh-profile-cpu [XH-PROFILE-CPU]] [--xh-profile-builtins [XH-PROFILE-BUILTINS]] [--xh-profile-memory [XH-PROFILE-MEMORY]] [--xh-link [XH-LINK]] [--] <command> <args>

~/Sites/8-drupal joachim$ drush9 cb-foo first
 [error]  TypeError: Argument 1 passed to Drush\Commands\CodeBuilder\CodeBuilderCommands::commandFoo() must be of the type array, string given in Drush\Commands\CodeBuilder\CodeBuilderCommands->commandFoo() (line 23 of /Users/joachim/Sites/8-drupal/drush/contrib/drupal-code-builder-drush/CodeBuilderCommands.php) #0 [internal function]: Drush\Commands\CodeBuilder\CodeBuilderCommands->commandFoo('first', Array)
#1 /Users/joachim/Sites/8-drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(235): call_user_func_array(Array, Array)
#2 /Users/joachim/Sites/8-drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(181): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#3 /Users/joachim/Sites/8-drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(147): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#4 /Users/joachim/Sites/8-drupal/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(399): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#5 /Users/joachim/Sites/8-drupal/vendor/symfony/console/Command/Command.php(264): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /Users/joachim/Sites/8-drupal/vendor/symfony/console/Application.php(892): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /Users/joachim/Sites/8-drupal/vendor/symfony/console/Application.php(228): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /Users/joachim/Sites/8-drupal/vendor/symfony/console/Application.php(130): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /Users/joachim/Sites/8-drupal/vendor/drush/drush/src/Boot/BaseBoot.php(117): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#10 /Users/joachim/Sites/8-drupal/vendor/drush/drush/includes/preflight.inc(77): Drush\Boot\BaseBoot->bootstrapAndDispatch()
#11 phar:///Users/joachim/bin/drush9/bin/drush.php(139): drush_main()
#12 /Users/joachim/bin/drush9(10): require('phar:///Users/j...')
#13 {main}.
TypeError: Argument 1 passed to Drush\Commands\CodeBuilder\CodeBuilderCommands::commandFoo() must be of the type array, string given in Drush\Commands\CodeBuilder\CodeBuilderCommands->commandFoo() (line 23 of /Users/joachim/Sites/8-drupal/drush/contrib/drupal-code-builder-drush/CodeBuilderCommands.php).
 [error]  Drush command terminated abnormally due to an unrecoverable error.
```

**Comment by greg-1-anderson** [comment]
This works in the [Robo examples](https://github.com/consolidation/Robo/blob/1.1.2/examples/RoboFile.php#L102).
```
$ ./robo -f examples try:array-args
➜  The parameters passed are:
array (
)
$ ./robo -f examples try:array-args a b c
➜  The parameters passed are:
array (
  0 => 'a',
  1 => 'b',
  2 => 'c',
)
```

**Comment by joachim-n** [comment]
It's definitely not working in Drush though!

At any rate, it's not quite what I'm after.

What I'd like to do is something like this:

```
  /**
   * @command foo
   * @param int $count The param count.
   */
  public function commandFoo($count) {
    // etc
  }
  
  /**
   * @hook interact foo
   */
  public function interactFoo(InputInterface $input, OutputInterface $output, AnnotationData $annotationData) {

    // Prompt for count if not given.

    $count = $input->getArgument('count');
    if ($count == 1) {
      $command->addArgument('first');
    }
    elseif ($count == 2) {
      $command->addArgument('first');
      $command->addArgument('second');
      
    }
    
   // Now prompt for first and second if they weren't given on the command line
  }
```

Silly example obviously, but then it would be possible for the user to do things like this on the command like and not always have to go through the interaction:

```
$ foo 1 first
$ foo 2 first second
$ foo 1 // get prompted for first
$ foo 2 first // get prompted for second
$ foo // get prompted for everything

```

It seems to me all I need here is to be able to get the symfony command object -- is there a method I can call to get it?

**Comment by greg-1-anderson** [comment]
Regarding Drush, if you want to use the features of the Annotated Command library, you must use the [symfony dispatch](https://github.com/drush-ops/drush/pull/2843) branch. Drush is only using a subset of this library on the 8.x and master branches. The Symfony Dispatch branch will be committed to master once done, prior to Drush 9.0.0 stable.

To achieve the results in the example above, you are better off declaring your command as follows:
```
public function commandFoo($count = 1, $first = '', $second = '') 
{
}
```
You can the test for and prompt for any missing argument.

If you need to dynamically add inputs in a hook to a command that does not already declare them, you should use options, not arguments.

**Comment by greg-1-anderson** [comment]
Oh, and regarding your other question, the annotated command library does not expose the symfony command object to most hooks. You'll get a reference to it in the Symfony hooks, of course. However, you should not try to modify it the way you propose at these times, because if you do, your adjustments will be invisible to the help command.
