### ISSUE TITLE
Docs for Initialize Hook are incorrect

### ISSUE THREAD

**Issue by joachim-n** [consolidation/annotated-command#270]
### Steps to reproduce

The docs say:

```
public function initSomeCommand(InputInterface $input, AnnotationData $annotationData)
```

But with this method signature, I get this error when doing `drush cc drush`:

```
Fatal error: Uncaught TypeError: Argument 1 passed to Drush\Commands\core_development\DevelopmentProjectCommands::yada() must be an instance of Drush\Commands\core_development\InputInterface, instance of Symfony\Component\Console\Input\ArgvInput given, called in /Users/joachim/Sites/drupal-core-composer/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php on line 47 and defined in /Users/joachim/Sites/drupal-core-composer/drush/Commands/core_development/DevelopmentProjectCommands.php:17
Stack trace:
#0 /Users/joachim/Sites/drupal-core-composer/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(47): Drush\Commands\core_development\DevelopmentProjectCommands->yada(Object(Symfony\Component\Console\Input\ArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#1 /Users/joachim/Sites/drupal-core-composer/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(36): Consolidation\AnnotatedCommand\Hooks\Dispatc in /Users/joachim/Sites/drupal-core-composer/drush/Commands/core_development/DevelopmentProjectCommands.php on line 17
```

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System Configuration
Which O.S. and PHP version are you using?

**Comment by joachim-n** [comment]
Argh sorry, scratch that, was my mistake.
